//Generate a new text document that defines a bunch of values
cfg_name=string(get_string("Name",""))
if cfg_name!=""{
    cfg_rup=real(get_integer("Ready Up Enabled",1))
    cfg_timeLimit=real(get_integer("Time Limit",10))
    cfg_respawnTime=real(get_integer("Respawn Time",5))
    cfg_capLimit=real(get_integer("Capture Limit",4))
    cfg_arenaWinLimit=real(get_integer("Arena Win Limit",5))
    cfg_deathmatchKillLimit=real(get_integer("Deathmatch Kill Limit",30))
    cfg_adcp=real(get_integer("ADCP Stopwatch Mode Enabled",0))
    cfg_minPlayers=real(get_integer("Minimum Players Per Team#-1 = No Limit",-1))
    cfg_maxPlayers=real(get_integer("Maximum Players Per Team#-1 = No Limit",-1))
    cfg_medCabs=real(get_integer("Med Cabinets Enabled",1))
    cfg_spawnDoors=real(get_integer("Spawn Doors Enabled",1))
    cfg_classlimits=real(get_integer("Classlimits#0 = None#1 = Highlander#2 = Custom",1))
    config_new_classlimits()
    
    show_message("Config created: "+cfg_name)
    
    cfgFile=file_text_open_write(working_directory+"\Configs\"+cfg_name+".cfg")
    file_text_write_string(cfgFile,"cfg_name="+'"'+cfg_name+'"');file_text_writeln(cfgFile)
    file_text_write_string(cfgFile,"cfg_rup="+string(cfg_rup));file_text_writeln(cfgFile)
    file_text_write_string(cfgFile,"cfg_timeLimit="+string(cfg_timeLimit));file_text_writeln(cfgFile)
    file_text_write_string(cfgFile,"cfg_respawnTime="+string(cfg_respawnTime));file_text_writeln(cfgFile)
    file_text_write_string(cfgFile,"cfg_capLimit="+string(cfg_capLimit));file_text_writeln(cfgFile)
    file_text_write_string(cfgFile,"cfg_arenaWinLimit="+string(cfg_arenaWinLimit));file_text_writeln(cfgFile)
    file_text_write_string(cfgFile,"cfg_deathmatchKillLimit="+string(cfg_deathmatchKillLimit));file_text_writeln(cfgFile)
    file_text_write_string(cfgFile,"cfg_minPlayers="+string(cfg_minPlayers));file_text_writeln(cfgFile)
    file_text_write_string(cfgFile,"cfg_maxPlayers="+string(cfg_maxPlayers));file_text_writeln(cfgFile)
    file_text_write_string(cfgFile,"cfg_medCabs="+string(cfg_medCabs));file_text_writeln(cfgFile)
    file_text_write_string(cfgFile,"cfg_spawnDoors="+string(cfg_spawnDoors));file_text_writeln(cfgFile)
    file_text_write_string(cfgFile,"cl_scout="+string(cl_scout));file_text_writeln(cfgFile)
    file_text_write_string(cfgFile,"cl_pyro="+string(cl_pyro));file_text_writeln(cfgFile)
    file_text_write_string(cfgFile,"cl_soldier="+string(cl_soldier));file_text_writeln(cfgFile)
    file_text_write_string(cfgFile,"cl_heavy="+string(cl_heavy));file_text_writeln(cfgFile)
    file_text_write_string(cfgFile,"cl_demoman="+string(cl_demoman));file_text_writeln(cfgFile)
    file_text_write_string(cfgFile,"cl_medic="+string(cl_medic));file_text_writeln(cfgFile)
    file_text_write_string(cfgFile,"cl_engineer="+string(cl_engineer));file_text_writeln(cfgFile)
    file_text_write_string(cfgFile,"cl_spy="+string(cl_spy));file_text_writeln(cfgFile)
    file_text_write_string(cfgFile,"cl_sniper="+string(cl_sniper));file_text_writeln(cfgFile)
    file_text_write_string(cfgFile,"cl_quote="+string(cl_quote));file_text_writeln(cfgFile)
    file_text_close(cfgFile)
}else{
    show_message("Config cannot have no name; exiting.")
}
